config/routes.rb
Rails.application.routes.draw do

  resources :dims

  resources :pres

  resources :focals

  resources :cases do
    get 'claim', on: :member
    get 'claimHypo', on: :member
  end


  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/pre.rb
class Pre < ActiveRecord::Base
  has_and_belongs_to_many :cases
  has_and_belongs_to_many :dims
end

app/controllers/pres_controller.rb
class PresController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @pres = Pre.all
    @newPre = Pre.new()
  end


  def new
    @dim = Dim.new(params[:name])
    @pres = Pre.all
    @AllFocal = Focal.all
  end


  def create
    @pre = Pre.new()
    @pre.content = params[:pre][:content]
    @pre.save
    redirect_to pres_path, :notice => "Prerequisite created."
  end


  def update
    @pre = Pre.find(params[:id])


    @pre.content = params[:pre][:content]


    @pre.save

    redirect_to pres_path, :notice => "Prerequisite updated."
  end


  def destroy
    pre = Pre.find(params[:id])
    pre.destroy
    redirect_to pres_path, :notice => "Prerequisite deleted."
  end



  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied, This is only for administrators."
    end
  end

  # def secure_params
  #   params.require(:user).permit(:role)
  # end
end

app/helpers/pre_helper.rb
module PreHelper
end

app/helpers/pres_helper.rb
module PresHelper
end

app/views/pres/_pre.html.erb
<td>
  <%=pre.id %>
</td>

<td>
  <%= form_for(pre) do |f| %>
      <%= f.text_area :content %>
    <%= f.submit 'Change', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete", pre_path(pre), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs')  %>
</td>

app/views/pres/index.html.erb
<div class="container">
  <div class="row">
    <h3>Factual Predicates</h3>
    <%= form_for (@newPre), url: {action: "create"} do |f| %>
        <p>Content:</p>
        <%= f.text_field :content %>
        <%= f.submit 'Create', :class => 'button-xs' %>
    <% end %>
    <div class="column">
      <table class="table">
        <tbody>
          <% @pres.each do |pre| %>
            <tr>
              <%= render pre %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>