config/routes.rb
Rails.application.routes.draw do

  resources :dims

  resources :pres

  resources :focals

  resources :cases do
    get 'claim', on: :member
    get 'claimHypo', on: :member
  end


  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/dim.rb
class Dim < ActiveRecord::Base
  has_and_belongs_to_many :pres
  has_and_belongs_to_many :focals

  def to_s
    return self.name
  end
end

app/controllers/dims_controller.rb
class DimsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @dims = Dim.all
  end

  def show
    @dim = Dim.find(params[:id])
    @pres = Pre.all
    @focals = Focal.all
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied. this is only for admin"
    end
  end


  def new
    @dim = Dim.new(params[:name])
    @pres = Pre.all
    @AllFocal = Focal.all
  end


  def create
    @dim = Dim.new()
    @dim.name = params[:dim][:name]

    Pre.all.each do |pre|
      if params[pre.id.to_s]
        @dim.pres<<pre
      end
    end
    Focal.all.each do |focal|
      if params["focal"+focal.id.to_s]
        @dim.focals<<focal
      end
    end
    @dim.save
    redirect_to dims_path, :notice => "dimemsion created."
  end


  def update
    @dim = Dim.find(params[:id])
    @allPres = Pre.all
    @dim.pres.delete(@allPres)
    @allPres.each do |pre|
      if params[pre.id.to_s]
        @dim.pres<<pre
      end
    end

    @AllFocals = Focal.all
    @dim.focals.delete(@AllFocals)
    @AllFocals.each do |fo|
      if params["focal"+fo.id.to_s]
        @dim.focals<<fo
      end
    end

    @dim.name = params[:dim][:name]
    @dim.claims = params[:dim][:claims]
    @dim.focalSlot = params[:dim][:focalSlot]
    @dim.proPlDr = params[:dim][:proPlDr]
    @dim.compType = params[:dim][:compType]


    @dim.save

    redirect_to dims_path, :notice => "dimemsion updated."
  end


  def destroy
    dim = Dim.find(params[:id])
    dim.destroy
    redirect_to dims_path, :notice => "Dimemsion deleted."
  end



  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied, This is only for administrators."
    end
  end

  # def secure_params
  #   params.require(:user).permit(:role)
  # end
end

app/helpers/dims_helper.rb
module DimsHelper
end

app/views/dims/_dim.html.erb
<td>
  <%= link_to dim.name, dim %>
</td>

<td>
  <%= link_to dim.created_at, dim %>
</td>

<td>
  <%= link_to("Delete Dimensions", dim_path(dim), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs')  %>
</td>

app/views/dims/index.html.erb
<div class="container">
  <div class="row">
    <h3>Dimensions</h3>
    <p>
    <%= link_to("Create Dimensions", { :controller=> 'dims', :action => 'new' }, :class => 'button-xs')  %>
    </p>
    <div class="column">
      <table class="table">
        <tbody>
          <% @dims.each do |dim| %>
            <tr>
              <%= render dim %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/dims/new.html.erb
<h3>New Dimensions</h3>
<%= form_for (@dim), url: {action: "create"} do |f| %>
    <p>Name:</p>
    <%= f.text_field :name %>
    <p>Claims:</p>
    <%= f.text_field :claims %>
    <p>Focal Slot:</p>
    <%= f.text_field :focalSlot %>
    <p>Pro plaintiff direction:</p>
    <%= f.text_field :proPlDr %>
    <p>Comparison type:</p>
    <%= f.text_field :compType %>


    <p>Prerequisites:</p>
    <% @pres.each do |pre| %>
        <p>
          <%= check_box_tag(pre.id,value = 1,checked = pre.dims.exists?(@dim)) %>
          <%= label_tag(pre.content, pre.content) %>
        </p>
    <% end %>


    <p>Focal slot prerequisite:</p>
    <% @AllFocal.each do |focal| %>
        <p>
          <%= check_box_tag("focal"+focal.id.to_s,value = 1,checked = focal.dims.exists?(@dim)) %>
          <%= label_tag(focal.content, focal.content) %>
        </p>
    <% end %>
    <%= f.submit 'Create', :class => 'button-xs' %>
<% end %>

app/views/dims/show.html.erb
<h3>Dimensions</h3>
<p>Name:  <%= @dim.name if @dim.name %></p>
<p>Created Time:  <%= @dim.created_at if @dim.created_at %></p>
<%= form_for(@dim) do |f| %>
   <p> Name:<%= f.text_field :name %></p>
    <p> Claims:<%= f.text_field :claims %></p>
    <p> Focal slot:<%= f.text_field :focalSlot %></p>
    <p> Pro plaintiff direction:<%= f.text_field :proPlDr %></p>
    <p> Comparison type:<%= f.text_field :compType %></p>

    <% @pres.each do |pre| %>
    <p>
      <%= check_box_tag(pre.id,value = 1,checked = pre.dims.exists?(@dim)) %>
      <%= label_tag(pre.content, pre.content) %>
    </p>
  <% end %>

    <h4>Focal Slot Prerequisites</h4>
    <% @focals.each do |focal| %>
        <p>
          <%= check_box_tag("focal"+focal.id.to_s,value = 1,checked = focal.dims.exists?(@dim)) %>
          <%= label_tag(focal.content, focal.content) %>
        </p>
    <% end %>
    <%= f.submit 'Update', :class => 'button-xs' %>
<% end %>