config/routes.rb
Rails.application.routes.draw do

  resources :dims

  resources :pres

  resources :focals

  resources :cases do
    get 'claim', on: :member
    get 'claimHypo', on: :member
  end


  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/focal.rb
class Focal < ActiveRecord::Base
  has_and_belongs_to_many :dims
end

app/controllers/focals_controller.rb
class FocalsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @focals = Focal.all
    @newFocal = Focal.new()
  end


  def new
    @dim = Dim.new(params[:name])
    @pres = Pre.all
    @AllFocal = Focal.all
  end


  def create
    @focal = Focal.new()
    @focal.content = params[:focal][:content]
    @focal.save
    redirect_to focals_path, :notice => "focal created."
  end


  def update
    @focal = Focal.find(params[:id])


    @focal.content = params[:focal][:content]


    @focal.save

    redirect_to focals_path, :notice => "focal updated."
  end


  def destroy
    focal = Focal.find(params[:id])
    focal.destroy
    redirect_to focals_path, :notice => "focal deleted."
  end



  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied, This is only for administrators."
    end
  end
end

app/helpers/focals_helper.rb
module FocalsHelper
end

app/views/focals/_focal.html.erb
<td>
  <%=focal.id %>
</td>

<td>
  <%= form_for(focal) do |f| %>
      <%= f.text_area :content %>
    <%= f.submit 'Change', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete", focal_path(focal), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs')  %>
</td>

app/views/focals/index.html.erb
<div class="container">
  <div class="row">
    <h3>Focal Slot Prerequisites</h3>
    <%= form_for (@newFocal), url: {action: "create"} do |f| %>
        <p>Content:</p>
        <%= f.text_field :content %>
        <%= f.submit 'Create', :class => 'button-xs' %>
    <% end %>
    <div class="column">
      <table class="table">
        <tbody>
          <% @focals.each do |focal| %>
            <tr>
              <%= render focal %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>